# Generated by Django 4.1.5 on 2023-05-08 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(blank=True, max_length=256, verbose_name='Операционная система')),
                ('processor', models.CharField(blank=True, max_length=256, verbose_name='Процессор')),
                ('memory', models.CharField(blank=True, max_length=256, verbose_name='Оперативная память')),
                ('graphics', models.CharField(blank=True, max_length=256, verbose_name='Видеокарта')),
                ('directx', models.CharField(blank=True, max_length=256, verbose_name='DirectX')),
                ('storage', models.CharField(blank=True, max_length=256, verbose_name='Свободное место на диске')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Название игры')),
                ('link', models.CharField(blank=True, max_length=256, verbose_name='Ссылка на игру')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
