# Generated by Django 4.1.5 on 2023-05-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcharacteristics',
            name='memory',
            field=models.IntegerField(blank=True, verbose_name='Оперативная память'),
        ),
        migrations.AlterField(
            model_name='systemcharacteristics',
            name='storage',
            field=models.IntegerField(blank=True, verbose_name='Свободное место на диске'),
        ),
    ]
