# Generated by Django 4.1.5 on 2023-05-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_systemcharacteristics_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcharacteristics',
            name='os',
            field=models.CharField(blank=True, choices=[('Windows 11', 'Windows 11'), ('Windows 10', 'Windows 10'), ('Windows 8.1', 'Windows 8.1'), ('Windows 8', 'Windows 8'), ('Windows 7', 'Windows 7'), ('Windows Vista', 'Windows Vista'), ('Windows XP', 'Windows XP')], max_length=256, verbose_name='Операционная система'),
        ),
    ]
