# Generated by Django 4.1.5 on 2023-05-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_game_critics_score_game_developer_game_directx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemcharacteristics',
            old_name='memory',
            new_name='ram',
        ),
    ]
