# Generated by Django 4.1.5 on 2023-05-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_memory_systemcharacteristics_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Разработчики'),
        ),
        migrations.AlterField(
            model_name='game',
            name='directx',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='DirectX'),
        ),
        migrations.AlterField(
            model_name='game',
            name='graphics',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Видеокарта'),
        ),
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка на игру'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='os',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Операционная система'),
        ),
        migrations.AlterField(
            model_name='game',
            name='processor',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='game',
            name='reviews',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Оценка пользователей'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Жанры'),
        ),
    ]
