# Generated by Django 4.1.5 on 2023-05-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_game_developer_alter_game_directx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='critics_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка критиков'),
        ),
    ]
